### ISSUE TITLE
Config vars as flag

### ISSUE THREAD

**Issue by michaelzoidl** [neumino/chateau#56]
A great feature would be to pass the config also in the CLI
For example when i want another port for the express-instance:
`$ chateau -expressPort 3001 `

**Comment by michaelzoidl** [comment]
*push*

**Comment by neumino** [comment]
A PR would be welcome.

**Comment by michaelzoidl** [comment]
done

**Comment by neumino** [comment]
Released in 0.3.14, thanks again!
